### ISSUE TITLE
Create Time Entry returns wrong location

### ISSUE THREAD

**Issue by dkoch8088** [paymoapp/api#1]
According to the _Creating a time entry_ section within entries.md:

If successful, the response will return 201 Created. The response header Location will contain a link for the new time entry.

After successfully creating a time entry using the api I was returned this location: https://app.paymoapp.com/entries/26307114.  Browsing to that URL got me this error:

![image](https://cloud.githubusercontent.com/assets/11398794/6566961/be193ac8-c67d-11e4-9064-e0469f7a39e5.png)

As far as I can tell, there is no direct view of time entries.  You must go through the time sheet of the related project.  If there is a direct URL to time entries I would be interested in knowing how to do that.

**Comment by paymo-old** [comment]
Thanks for reporting this. The URL in Location header was corrected.
