### ISSUE TITLE
Update hooks

### ISSUE THREAD

**Issue by ahorndesign** [paymoapp/api#21]
The insert hooks currently provided are not enough for most integrations. To make the API really useful, we also need update hooks. These can trigger any time an entry is edited. They don't have to contain information on the edit itself, it can be pulled separately. Use-case examples are:

- **For tasks:** there is currently no way to detect that a task has been marked "complete", so no full integration with a to-do app is possible
- **For invocices** no way to detect the status change from "Draft" to "Send". This is super important as one can save an invoice a couple of times while creating it, but only need an integration when it is complete (like send it to the accountants office)
- **For clients** so we would be able to update an address book when contacts change

**Comment by alasdaircr** [comment]
@ahorndesign see #20 

I'm also looking for these. In the meantime I'm polling every minute but this is not nice for UX.

**Comment by paymo-old** [comment]
We have added `update` and `delete` hooks.
