### ISSUE TITLE
user_id sent via API doesn't reflect as Creator in Paymo

### ISSUE THREAD

**Issue by alasdaircr** [paymoapp/api#22]
Hello,

Tasks created with ``user_id`` specified do not retain this as the 'Creator' in the application. The Creator is instead the user who's credentials were used over the API.

**Comment by paymo-old** [comment]
`user_id` is always the ID of the task creator. If you specify another `user_id` in the request, it will be overridden with the ID of the authenticated user making the request.

**Comment by alasdaircr** [comment]
Hmm - it would make things much simpler if the API respected user_id being supplied in this instance, as to fix this I would need to manage and store an API key for each user.

**Comment by alasdaircr** [comment]
(I'm meaning only in the POST new object instance state)

**Comment by alasdaircr** [comment]
Otherwise please add 'read-only' specifier to the documentation for this field and don't allow it to be specified in a POST request.
