### ISSUE TITLE
Filtering tasks with 'and' in the query

### ISSUE THREAD

**Issue by alasdaircr** [paymoapp/api#23]
Hello if I query the tasks endpoint like this:

`tasklist_id=10000 and name="Just some name and then something else."`

I receive a 400 error with the following message

`[message] => Invalid condition in "where" param: then something else."`

There must be something up with the string parsing?

The query is being urlencoded correctly - other queries without `and` in the string filter return successfully.

**Comment by paymo-old** [comment]
Hi,
Thanks for reporting this. It was fixed.
