### ISSUE TITLE
Feature Request OrderBy

### ISSUE THREAD

**Issue by sgasser** [paymoapp/api#3]
OrderBy to get a request order by a field.
For example:
- /api/tasks?order=due_date (order due_date ascending) 
- /api/tasks?order=-due_date (order due_date descending)

**Comment by paymo-old** [comment]
It is possible to order the response by specifying `order` param, like in the example below:
/api/tasks?order=due_date
/api/tasks?order=due_date asc
/api/tasks?order=due_date desc
