### ISSUE TITLE
Webhook model.update.Task fires too often

### ISSUE THREAD

**Issue by daniellobrunello** [paymoapp/api#38]
Opening and closing a task without any changes triggers the model.update.Task webhook.
Is there a reason that this is considered as an update?

This also reflects on the "Last Events" section in the project overview.

I'm using this hook to trigger custom Slack messages. Is there another possibility to check for actual changes of the task?

Great API btw.
Thanks.

**Comment by paymo-old** [comment]
Changing the status of a task is considered an update. At the moment there is no list of changed fields in the webhook request.

**Comment by daniellobrunello** [comment]
I'm not talking about changing the status of the task. 
Opening and closing without any task manipulation is considered as an update.

**Comment by paymo-old** [comment]
We could not replicate your behaviour. Please send to support@paymoapp.com steps to reproduce the problem.
