### ISSUE TITLE
Feature Request Fields

### ISSUE THREAD

**Issue by sgasser** [paymoapp/api#4]
Fields to get only fields requested like in include (?include=project.name).
For example:
api/tasks?fields=name,due_date

The Response should be:

``` json
{
   "tasks": [      
      {
         "name": "Design",
         "due_date": null
      },
      {
         "name": "Testing",
         "due_date": "2014-10-30"
      }
   ]
}
```

**Comment by paymo-old** [comment]
It is currently possible to include only the desired fields using the same 'include' param.
For your example it will be:
api/tasks?include=name,due_date
