### ISSUE TITLE
Task statuses

### ISSUE THREAD

**Issue by maxguru** [paymoapp/api#41]
I may be missing something, however, /tasks requests return 'status_id' which contain an ID.  However, I am not seeing how to get a list of task statuses.  There is a method for getting a list of project statuses, but not task statuses.  Am I missing something?

**Comment by daylightstudio** [comment]
I have the same question...

**Comment by nikisbeta** [comment]
Can you answer please? Will be statuslist available?

**Comment by paymo-old** [comment]
We'll make the changes to the docs when task statuses API will be made public.

**Comment by paymo-old** [comment]
We've updated the docs with project workflows, task statuses and task priorities.
