### ISSUE TITLE
how to get hours spent on a project by month

### ISSUE THREAD

**Issue by bambamboole** [paymoapp/api#42]
hi,

I have to get the hours spent on a project from the api in a specific month (and current month).
In the first step I dont care about single tasks. Just simple times spent on a project basis.

Is this possible?

**Comment by paymo-old** [comment]
You have to create a report and give it as input params the date range (or a preset such as `this_month`) and the list of projects. Report type may be `temp` if you do not want to save it in your reports list. See https://github.com/paymoapp/api/blob/master/sections/reports.md
