### ISSUE TITLE
Hours spent on a project

### ISSUE THREAD

**Issue by federicovezzoli** [paymoapp/api#48]
Hi Guys, I'm looking to retrieve the total hours spent on a project, but couldn't find them anywhere, am I missing something?

thanks a lot.

**Comment by paymo-old** [comment]
Hi,
You can retrieve the amount of time spent on a project by a user by creating a temporary timesheet report, e.g.:

```
POST https://app.paymoapp.com/api/reports
Content-type: application/json

{
    "type": "temp",
    "projects": [12345],
    "users": [789],
    "date_interval": "all_time"
}
```

**Comment by federicovezzoli** [comment]
Thanks, is there a way to easily include all the users?

**Comment by paymo-old** [comment]
Yes, use ```"users": "all"```
