### ISSUE TITLE
Time entry description contains HTML

### ISSUE THREAD

**Issue by iamso** [paymoapp/api#50]
Hi 

I have written an export tool using the Paymo API and I have noticed, that recently all time entry descriptions contain html, mostly `<p>` tags. At first, it was only the ones, entered or edited through the web interface, then it started to affect the ones from the desktop widget as well. I made an export today and all descriptions from every time entry contained the `<p>` tag and all descriptions were entered through the widget.

This is very inconvenient for processing and a little unusual for an API.

Could you change this back? Or is there a way, you could add an HTML-free version of the description to the output?

Thanks
Steve

**Comment by ldimlight** [comment]
Hi

The recent version of Widget stores HTML formatted text into the description. The API on the other hand has no preference for the type of content stored in entry's description. 
You could strip HTML tags upon data retrieval on your API consumer side.

**Comment by iamso** [comment]
Hi @ldimlight that's what I ended up doing. 
Just thought I'd ask you guys about it first.

Thanks
Steve
