### ISSUE TITLE
API Request failed

### ISSUE THREAD

**Issue by mirco-waldvogel** [paymoapp/api#61]
Every Request with api/tasks?where=project_id=[ProjectId] and with api/projects/[ProjectID]
returns 'Access to project denied' but with the same token and request I can get the full list of Projects and also of Tasks.

**Comment by paymo-old** [comment]
Is the project with id=[ProjectId] in the list of projects?

**Comment by mirco-waldvogel** [comment]
Yes on the request with projects is the project included which I requesting on the single project request.

**Comment by paymo-old** [comment]
Please send the project id and the id/email of the user making the request to support@paymoapp.com and we'll have a look.
