### ISSUE TITLE
Retrieve Tasks

### ISSUE THREAD

**Issue by mcmsys** [paymoapp/api#65]
I have a program that pulls in all tasks.  This has been working using the following code for a few years and has been pulling down 5900 records recently.  Suddenly it is only pulling down 5000 records (not the newer ones).  Any reason for this?

curl -u {api key}:X https://app.paymoapp.com/api/tasks?format=xml > c:\api\tasks.xml

**Comment by paymo-old** [comment]
We do not recommend pulling all the tasks in a single API call if we're talking about thousands of tasks.
If this is a recurring action, we suggest implementing a webhook to be notified when any new tasks are added/updated/deleted: https://github.com/paymoapp/api/blob/master/sections/webhooks.md
