### ISSUE TITLE
Unable to Query Project Retainer Information from API

### ISSUE THREAD

**Issue by swizzmagik** [paymoapp/api#66]
I can see `retainer_id` but not any endpoints to get retainer info beyond this. Is it possible to access this info through the API?

![image](https://github.com/paymoapp/api/assets/3955528/4b0a3a5e-9a7f-44d3-a430-306b9ee49ee6)

**Comment by paymo-old** [comment]
Project Retainer API is not public at the moment.

**Comment by swizzmagik** [comment]
Any updates or plans on this?

**Comment by mtebusi** [comment]
Yes, please make this public. Need to use this for integration with external billing system and for client visibility purposes. 

Thanks
