### ISSUE TITLE
Filtering includes

### ISSUE THREAD

**Issue by JamesHorsley** [paymoapp/api#8]
Is there any way to filter includes - e.g. I have a GUI app I have written to add time on a caleendar with more precision and extra features compared to the timesheets web app (e.g. wrap one entry around another etc) - in this I need to load a list of clients, their projects and the taskslist and tasks for each project - but I noramally only want the active ones - so I was going to use a call to clients with where active=True and include of projects,projects.tasklists,projects.tasklists.tasks to get the client's projects and tasklists with child tasks for each.  But how can I get just active ones on these child parts?

**Comment by paymo-old** [comment]
You can filter the includes in the `where` param, like so:
https://app.paymoapp.com/api/clients?include=projects,projects.tasklists,projects.tasklists.tasks&where=active=true and projects.active=true and projects.tasklists.tasks.complete=false

**Comment by sgasser** [comment]
On tasks it's not working:

```
https://app.paymoapp.com/api/tasks?where=due_date=2012-05-04 and project.active=true&include=project,tasklist
```

**Comment by paymo-old** [comment]
If you want to limit the response only to the tasks from active projects, you cannot do that by adding a `where` rule for `include`. You should start from `projects` and include `tasks`, using a `where` condition for the projects list.

**Comment by sgasser** [comment]
How it works on entries?
I want to filter entries of a time_interval and by a e-mail:

`https://app.paymoapp.com/api/users?include=name,entries.description&where=email=email@tld.com and entries.time_interval in ("2015-03-20T00:00:00", "2015-03-23T00:00:00")`

**Comment by paymo-old** [comment]
Right now, filtering entries using time_interval in (A,B) works only making the request to the /api/entries endpoint. For where on includes, you should use entries.start_time>START_TIMESTAMP and entries.end_time<END_TIMESTAMP.

Like so: 
https://app.paymoapp.com/api/users?include=name,entries.description&where=email=email@tld.com and entries.start_time>1426802400 and entries.end_time<1427061600

**Comment by sgasser** [comment]
Thanks.
How I can order the entries?
entries_order=start_time does not works

**Comment by paymo-old** [comment]
Right now, you cannot order items in an include. In case of this request, https://app.paymoapp.com/api/users?include=name,entries.description 
you can only order users.
