### ISSUE TITLE
Format of Due Date in Tasks

### ISSUE THREAD

**Issue by JamesHorsley** [paymoapp/api#9]
Dates are meant to be ISO 8601 format but the due date in tasks comes back as simple yyyy-mm-dd which is of course not ISO 8601 and may imply the incorrect due date if the user has to deal with different time zones .. and more irritatingly it broke my code that uses RestSharp which does not allow you to specify date format at a per field level - just per call - and when I get back my list of clients, their projects and tasks it blows up - because some dates are ISO 8601 as specified but this due date isn't

**Comment by ldimlight** [comment]
ISO 8601 for dates (without time) allow for YYYY-MM-DD format, see http://en.wikipedia.org/wiki/ISO_8601
In Paymo, a due date for a task does not contain the time information. So the representation is correct.

**Comment by JamesHorsley** [comment]
Sorry - my mistake ... pity RestSharp does not allow format specified at a field level - it would also help for documentation to make clear which date fields are in which format - actually I see they are all set as date not datetime - so I'm wrong again!
